name: un_intercambio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Íconos y UI
  cupertino_icons: ^1.0.8

  # Calendario interactivo
  table_calendar: ^3.0.9

  # Gráficos y visualización de datos
  fl_chart: ^0.70.2

  # Manejo de archivos
  flutter_file_dialog: ^3.0.0
  file_picker: ^8.0.0

  # Internacionalización
  intl: ^0.19.0

  # Estado y gestión de dependencias con Riverpod y Provider
  flutter_riverpod: ^2.4.9
  provider: 6.1.2
  dio: ^5.4.0

  # Serialización y generación de código
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  # Peticiones HTTP
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.6

  # Pruebas en Flutter
  flutter_test:
    sdk: flutter

  # Buenas prácticas de código
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: UNintercambioCustomIcons
      fonts:
        - asset: assets/fonts/UNintercambioCustomIcons.ttf
